### ISSUE TITLE
./jupytergraffiti/build_and_run.sh command from readme doesn't work

### ISSUE THREAD

**Issue by evanpjensen** [willkessler/jupytergraffiti#51]
```
./jupytergraffiti/build_and_run.sh

(Re)Building docker image.
Sending build context to Docker daemon  1.324MB
Step 1/14 : FROM jupyter/datascience-notebook
latest: Pulling from jupyter/datascience-notebook
423ae2b273f4: Pull complete 
de83a2304fa1: Pull complete 
f9a83bce3af0: Pull complete 
b6b53be908de: Pull complete 
eac80289c2c5: Pull complete 
b770752562e4: Pull complete 
f9794a341066: Pull complete 
157147dea6d0: Pull complete 
a9cc9783b8fb: Pull complete 
81c84a76cf52: Pull complete 
7384c14c5b8f: Pull complete 
96e5dd8ec1dd: Pull complete 
54ff1acfdce5: Pull complete 
9e8ff2458372: Pull complete 
d281f5d9be70: Pull complete 
4e3bcc2e9b25: Pull complete 
37dd16c123a0: Pull complete 
7512a97e9059: Pull complete 
7e65510f9c51: Pull complete 
199d2d12a4f0: Pull complete 
87e795f2ae07: Pull complete 
1ebe410b718e: Pull complete 
28b79d334c41: Pull complete 
6ea486a7cf22: Pull complete 
fc2901daa1a3: Pull complete 
0dccbd613972: Pull complete 
21bba711623e: Pull complete 
Digest: sha256:b672f926e0f2ddb4b68172d33c0fea64f8f66651e86e233dc12894ddf7299b98
Status: Downloaded newer image for jupyter/datascience-notebook:latest
 ---> ce97927bafa2
Step 2/14 : USER root
 ---> Running in 09374e988f97
Removing intermediate container 09374e988f97
 ---> 89a83cea4188
Step 3/14 : RUN curl -sL https://deb.nodesource.com/setup_11.x | sudo bash - && apt-get install -y nodejs
 ---> Running in 6d177fc7f9cc

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 11.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium" (recommended)
   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...


## Installing the NodeSource Node.js 11.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [7,904 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [832 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [861 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [35.2 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [11.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [48.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,362 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,155 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2,496 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4,247 B]
Fetched 17.7 MB in 8s (2,103 kB/s)
Reading package lists...

## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg > /dev/null 2>&1

## Confirming "bionic" is supported...

+ wget -qO /dev/null -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/bionic/Release'

## Adding the NodeSource signing key to your keyring...

+ wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

## Creating apt sources list file for the NodeSource Node.js 11.x repo...

+ echo 'deb https://deb.nodesource.com/node_11.x bionic main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_11.x bionic main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:2 https://deb.nodesource.com/node_11.x bionic InRelease [4,584 B]
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:6 https://deb.nodesource.com/node_11.x bionic/main amd64 Packages [768 B]
Fetched 5,352 B in 1s (6,432 B/s)
Reading package lists...

## Run `sudo apt-get install -y nodejs` to install Node.js 11.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
Need to get 16.2 MB of archives.
After this operation, 77.9 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_11.x bionic/main amd64 nodejs amd64 11.15.0-1nodesource1 [16.2 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 16.2 MB in 2s (9,432 kB/s)
Selecting previously unselected package nodejs.
(Reading database ... 120073 files and directories currently installed.)
Preparing to unpack .../nodejs_11.15.0-1nodesource1_amd64.deb ...
Unpacking nodejs (11.15.0-1nodesource1) ...
Setting up nodejs (11.15.0-1nodesource1) ...
Removing intermediate container 6d177fc7f9cc
 ---> fcb26a88663f
Step 4/14 : RUN mkdir -p /opt/jupytergraffiti
 ---> Running in e34ecab1c85c
Removing intermediate container e34ecab1c85c
 ---> 89e23992ed0d
Step 5/14 : COPY . /opt/jupytergraffiti
 ---> 9f6070af249d
Step 6/14 : WORKDIR /opt/jupytergraffiti
 ---> Running in 369d58b0d429
Removing intermediate container 369d58b0d429
 ---> 7630b902da01
Step 7/14 : RUN cd /opt/jupytergraffiti && npm install && npm run build &&        jupyter nbextension install graffiti-dist && jupyter nbextension enable graffiti-dist/graffiti
 ---> Running in f3412255b6f7
npm WARN jupytergraffiti@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 570 packages from 353 contributors and audited 10108 packages in 14.77s
found 288 vulnerabilities (287 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

> jupytergraffiti@1.0.0 build /opt/jupytergraffiti
> rm -rf graffiti-dist build ../build_for_pip/code-prep && node_modules/gulp/bin/gulp.js prebuild && node node_modules/.bin/r.js -o build.js && node_modules/gulp/bin/gulp.js moveStyles && node node_modules/.bin/r.js -o ../build_for_pip/buildPip.js && node_modules/gulp/bin/gulp.js pipMoveStyles

[17:14:22] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[17:14:22] Using gulpfile /opt/jupytergraffiti/gulpfile.babel.js
[17:14:22] Starting 'prebuild'...
[17:14:22] Starting 'main'...
[17:14:22] Starting 'jsFiles'...
[17:14:22] Starting 'pipMain'...
[17:14:22] Starting 'pipJsFiles'...
[17:14:23] Finished 'main' after 533 ms
[17:14:23] Finished 'pipMain' after 589 ms
[17:14:30] Finished 'jsFiles' after 7.64 s
[17:14:30] Finished 'pipJsFiles' after 7.64 s
[17:14:30] Finished 'prebuild' after 7.64 s

Tracing dependencies for: main
Uglify file: /opt/jupytergraffiti/graffiti-dist/graffiti.js

/opt/jupytergraffiti/graffiti-dist/graffiti.js
----------------
/opt/jupytergraffiti/build/js/LZString.js
/opt/jupytergraffiti/build/js/utils.js
/opt/jupytergraffiti/build/js/localizer.js
/opt/jupytergraffiti/build/js/xterm/xterm.js
/opt/jupytergraffiti/build/js/xterm/addons/fit/fit.js
/opt/jupytergraffiti/build/js/terminals.js
/opt/jupytergraffiti/build/js/state.js
/opt/jupytergraffiti/build/js/hark.js
/opt/jupytergraffiti/build/js/audio.js
/opt/jupytergraffiti/build/js/batchRunner.js
/opt/jupytergraffiti/build/js/storage.js
/opt/jupytergraffiti/build/js/sticker.js
/opt/jupytergraffiti/build/js/selectionSerializer.js
/opt/jupytergraffiti/build/js/workspace.js
/opt/jupytergraffiti/build/js/graffiti.js
/opt/jupytergraffiti/build/js/loader.js
/opt/jupytergraffiti/build/js/initExtension.js
/opt/jupytergraffiti/build/main.js

[17:14:35] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[17:14:36] Using gulpfile /opt/jupytergraffiti/gulpfile.babel.js
[17:14:36] Starting 'moveStyles'...
[17:14:36] Finished 'moveStyles' after 49 ms
Error: Error: ENOENT: no such file or directory, lstat '/opt/build_for_pip/buildPip.js'
    at Object.realpathSync (fs.js:1566:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupytergraffiti@1.0.0 build: `rm -rf graffiti-dist build ../build_for_pip/code-prep && node_modules/gulp/bin/gulp.js prebuild && node node_modules/.bin/r.js -o build.js && node_modules/gulp/bin/gulp.js moveStyles && node node_modules/.bin/r.js -o ../build_for_pip/buildPip.js && node_modules/gulp/bin/gulp.js pipMoveStyles`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupytergraffiti@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jovyan/.npm/_logs/2020-03-26T17_14_36_425Z-debug.log
The command '/bin/sh -c cd /opt/jupytergraffiti && npm install && npm run build &&        jupyter nbextension install graffiti-dist && jupyter nbextension enable graffiti-dist/graffiti' returned a non-zero code: 1
Starting Jupyter Server container with Graffiti Extension...
Unable to find image 'jupytergraffiti:latest' locally
docker: Error response from daemon: pull access denied for jupytergraffiti, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by evanpjensen** [comment]
Here is the contents of /home/jovyan/.npm/_logs/2020-03-26T17_14_36_425Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/conda/bin/node', '/opt/conda/bin/npm', 'run', 'build' ]
2 info using npm@6.13.7
3 info using node@v13.10.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jupytergraffiti@1.0.0~prebuild: jupytergraffiti@1.0.0
6 info lifecycle jupytergraffiti@1.0.0~build: jupytergraffiti@1.0.0
7 verbose lifecycle jupytergraffiti@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle jupytergraffiti@1.0.0~build: PATH: /opt/conda/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/jupytergraffiti/node_modules/.bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle jupytergraffiti@1.0.0~build: CWD: /opt/jupytergraffiti
10 silly lifecycle jupytergraffiti@1.0.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'rm -rf graffiti-dist build ../build_for_pip/code-prep && node_modules/gulp/bin/gulp.js prebuild && node node_modules/.bin/r.js -o build.js && node_modules/gulp/bin/gulp.js moveStyles && node node_modules/.bin/r.js -o ../build_for_pip/buildPip.js && node_modules/gulp/bin/gulp.js pipMoveStyles'
10 silly lifecycle ]
11 silly lifecycle jupytergraffiti@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle jupytergraffiti@1.0.0~build: Failed to exec build script
13 verbose stack Error: jupytergraffiti@1.0.0 build: `rm -rf graffiti-dist build ../build_for_pip/code-prep && node_modules/gulp/bin/gulp.js prebuild && node node_modules/.bin/r.js -o build.js && node_modules/gulp/bin/gulp.js moveStyles && node node_modules/.bin/r.js -o ../build_for_pip/buildPip.js && node_modules/gulp/bin/gulp.js pipMoveStyles`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/conda/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:316:20)
13 verbose stack     at ChildProcess.<anonymous> (/opt/conda/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:316:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jupytergraffiti@1.0.0
15 verbose cwd /opt/jupytergraffiti
16 verbose Linux 5.0.0-38-generic
17 verbose argv "/opt/conda/bin/node" "/opt/conda/bin/npm" "run" "build"
18 verbose node v13.10.1
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error jupytergraffiti@1.0.0 build: `rm -rf graffiti-dist build ../build_for_pip/code-prep && node_modules/gulp/bin/gulp.js prebuild && node node_modules/.bin/r.js -o build.js && node_modules/gulp/bin/gulp.js moveStyles && node node_modules/.bin/r.js -o ../build_for_pip/buildPip.js && node_modules/gulp/bin/gulp.js pipMoveStyles`
22 error Exit status 1
23 error Failed at the jupytergraffiti@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by willkessler** [comment]
Thanks for this report, I will update that script.

**Comment by willkessler** [comment]
I pushed a fix. Please git pull and retry, or simply replace `jupytergraffiti/Dockerfile` with the newest version here:

https://github.com/willkessler/jupytergraffiti/blob/master/jupytergraffiti/Dockerfile

**Comment by willkessler** [comment]
@evanpjensen : Reopen this issue if you still have problems...

**Comment by willkessler** [comment]
Since there's beenno answer from @evanpjensen I'm assuming this is no longer an issue, so closing...
